//
// File generated by rootcint at Sun Jul 28 14:34:17 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME DataStruct_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "DataStruct_dict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TDCHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TDCHit(void *p = 0);
   static void *newArray_TDCHit(Long_t size, void *p);
   static void delete_TDCHit(void *p);
   static void deleteArray_TDCHit(void *p);
   static void destruct_TDCHit(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TDCHit*)
   {
      ::TDCHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDCHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TDCHit", ::TDCHit::Class_Version(), "./libDataStruct.h", 17,
                  typeid(::TDCHit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TDCHit::Dictionary, isa_proxy, 4,
                  sizeof(::TDCHit) );
      instance.SetNew(&new_TDCHit);
      instance.SetNewArray(&newArray_TDCHit);
      instance.SetDelete(&delete_TDCHit);
      instance.SetDeleteArray(&deleteArray_TDCHit);
      instance.SetDestructor(&destruct_TDCHit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TDCHit*)
   {
      return GenerateInitInstanceLocal((::TDCHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TDCHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void NIGIRIHit_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NIGIRIHit(void *p = 0);
   static void *newArray_NIGIRIHit(Long_t size, void *p);
   static void delete_NIGIRIHit(void *p);
   static void deleteArray_NIGIRIHit(void *p);
   static void destruct_NIGIRIHit(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NIGIRIHit*)
   {
      ::NIGIRIHit *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NIGIRIHit >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NIGIRIHit", ::NIGIRIHit::Class_Version(), "./libDataStruct.h", 35,
                  typeid(::NIGIRIHit), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NIGIRIHit::Dictionary, isa_proxy, 4,
                  sizeof(::NIGIRIHit) );
      instance.SetNew(&new_NIGIRIHit);
      instance.SetNewArray(&newArray_NIGIRIHit);
      instance.SetDelete(&delete_NIGIRIHit);
      instance.SetDeleteArray(&deleteArray_NIGIRIHit);
      instance.SetDestructor(&destruct_NIGIRIHit);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NIGIRIHit*)
   {
      return GenerateInitInstanceLocal((::NIGIRIHit*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NIGIRIHit*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void NIGIRI_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_NIGIRI(void *p = 0);
   static void *newArray_NIGIRI(Long_t size, void *p);
   static void delete_NIGIRI(void *p);
   static void deleteArray_NIGIRI(void *p);
   static void destruct_NIGIRI(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::NIGIRI*)
   {
      ::NIGIRI *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::NIGIRI >(0);
      static ::ROOT::TGenericClassInfo 
         instance("NIGIRI", ::NIGIRI::Class_Version(), "./libDataStruct.h", 131,
                  typeid(::NIGIRI), ::ROOT::DefineBehavior(ptr, ptr),
                  &::NIGIRI::Dictionary, isa_proxy, 4,
                  sizeof(::NIGIRI) );
      instance.SetNew(&new_NIGIRI);
      instance.SetNewArray(&newArray_NIGIRI);
      instance.SetDelete(&delete_NIGIRI);
      instance.SetDeleteArray(&deleteArray_NIGIRI);
      instance.SetDestructor(&destruct_NIGIRI);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::NIGIRI*)
   {
      return GenerateInitInstanceLocal((::NIGIRI*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::NIGIRI*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TDCHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TDCHit::Class_Name()
{
   return "TDCHit";
}

//______________________________________________________________________________
const char *TDCHit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TDCHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TDCHit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TDCHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TDCHit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TDCHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TDCHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TDCHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr NIGIRIHit::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NIGIRIHit::Class_Name()
{
   return "NIGIRIHit";
}

//______________________________________________________________________________
const char *NIGIRIHit::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRIHit*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NIGIRIHit::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRIHit*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NIGIRIHit::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRIHit*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NIGIRIHit::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRIHit*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
atomic_TClass_ptr NIGIRI::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *NIGIRI::Class_Name()
{
   return "NIGIRI";
}

//______________________________________________________________________________
const char *NIGIRI::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRI*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int NIGIRI::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRI*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void NIGIRI::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRI*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *NIGIRI::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::NIGIRI*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void NIGIRI::Streamer(TBuffer &R__b)
{
   // Stream an object of class NIGIRI.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(NIGIRI::Class(),this);
   } else {
      R__b.WriteClassBuffer(NIGIRI::Class(),this);
   }
}

//______________________________________________________________________________
void NIGIRI::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NIGIRI.
      TClass *R__cl = ::NIGIRI::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fmult", &fmult);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fhits", (void*)&fhits);
      R__insp.InspectMember("vector<NIGIRIHit*>", (void*)&fhits, "fhits.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NIGIRI(void *p) {
      return  p ? new(p) ::NIGIRI : new ::NIGIRI;
   }
   static void *newArray_NIGIRI(Long_t nElements, void *p) {
      return p ? new(p) ::NIGIRI[nElements] : new ::NIGIRI[nElements];
   }
   // Wrapper around operator delete
   static void delete_NIGIRI(void *p) {
      delete ((::NIGIRI*)p);
   }
   static void deleteArray_NIGIRI(void *p) {
      delete [] ((::NIGIRI*)p);
   }
   static void destruct_NIGIRI(void *p) {
      typedef ::NIGIRI current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::NIGIRI

//______________________________________________________________________________
void NIGIRIHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class NIGIRIHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(NIGIRIHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(NIGIRIHit::Class(),this);
   }
}

//______________________________________________________________________________
void NIGIRIHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class NIGIRIHit.
      TClass *R__cl = ::NIGIRIHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evt_type", &evt_type);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "overrange", &overrange);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "losttrigger", &losttrigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "evt", &evt);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "b", &b);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ch", &ch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ts", &ts);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "finets", &finets);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "cshort", &cshort);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "clong", &clong);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "baseline", &baseline);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nsample", &nsample);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pulse", (void*)&pulse);
      R__insp.InspectMember("vector<UShort_t>", (void*)&pulse, "pulse.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdcmult", &tdcmult);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdc_ch", (void*)&tdc_ch);
      R__insp.InspectMember("vector<UShort_t>", (void*)&tdc_ch, "tdc_ch.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tdc_t", (void*)&tdc_t);
      R__insp.InspectMember("vector<UShort_t>", (void*)&tdc_t, "tdc_t.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "qdcmult", &qdcmult);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "qdc_ch", (void*)&qdc_ch);
      R__insp.InspectMember("vector<UShort_t>", (void*)&qdc_ch, "qdc_ch.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "qdc_h", (void*)&qdc_h);
      R__insp.InspectMember("vector<UShort_t>", (void*)&qdc_h, "qdc_h.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_NIGIRIHit(void *p) {
      return  p ? new(p) ::NIGIRIHit : new ::NIGIRIHit;
   }
   static void *newArray_NIGIRIHit(Long_t nElements, void *p) {
      return p ? new(p) ::NIGIRIHit[nElements] : new ::NIGIRIHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_NIGIRIHit(void *p) {
      delete ((::NIGIRIHit*)p);
   }
   static void deleteArray_NIGIRIHit(void *p) {
      delete [] ((::NIGIRIHit*)p);
   }
   static void destruct_NIGIRIHit(void *p) {
      typedef ::NIGIRIHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::NIGIRIHit

//______________________________________________________________________________
void TDCHit::Streamer(TBuffer &R__b)
{
   // Stream an object of class TDCHit.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(TDCHit::Class(),this);
   } else {
      R__b.WriteClassBuffer(TDCHit::Class(),this);
   }
}

//______________________________________________________________________________
void TDCHit::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TDCHit.
      TClass *R__cl = ::TDCHit::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ch", &ch);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t", &t);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TDCHit(void *p) {
      return  p ? new(p) ::TDCHit : new ::TDCHit;
   }
   static void *newArray_TDCHit(Long_t nElements, void *p) {
      return p ? new(p) ::TDCHit[nElements] : new ::TDCHit[nElements];
   }
   // Wrapper around operator delete
   static void delete_TDCHit(void *p) {
      delete ((::TDCHit*)p);
   }
   static void deleteArray_TDCHit(void *p) {
      delete [] ((::TDCHit*)p);
   }
   static void destruct_TDCHit(void *p) {
      typedef ::TDCHit current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::TDCHit

namespace ROOTDict {
   void vectorlENIGIRIHitmUgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlENIGIRIHitmUgR_Dictionary();
   static void *new_vectorlENIGIRIHitmUgR(void *p = 0);
   static void *newArray_vectorlENIGIRIHitmUgR(Long_t size, void *p);
   static void delete_vectorlENIGIRIHitmUgR(void *p);
   static void deleteArray_vectorlENIGIRIHitmUgR(void *p);
   static void destruct_vectorlENIGIRIHitmUgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<NIGIRIHit*>*)
   {
      vector<NIGIRIHit*> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<NIGIRIHit*>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<NIGIRIHit*>", -2, "prec_stl/vector", 49,
                  typeid(vector<NIGIRIHit*>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlENIGIRIHitmUgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<NIGIRIHit*>) );
      instance.SetNew(&new_vectorlENIGIRIHitmUgR);
      instance.SetNewArray(&newArray_vectorlENIGIRIHitmUgR);
      instance.SetDelete(&delete_vectorlENIGIRIHitmUgR);
      instance.SetDeleteArray(&deleteArray_vectorlENIGIRIHitmUgR);
      instance.SetDestructor(&destruct_vectorlENIGIRIHitmUgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<NIGIRIHit*> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<NIGIRIHit*>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlENIGIRIHitmUgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<NIGIRIHit*>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlENIGIRIHitmUgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<NIGIRIHit*> : new vector<NIGIRIHit*>;
   }
   static void *newArray_vectorlENIGIRIHitmUgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<NIGIRIHit*>[nElements] : new vector<NIGIRIHit*>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlENIGIRIHitmUgR(void *p) {
      delete ((vector<NIGIRIHit*>*)p);
   }
   static void deleteArray_vectorlENIGIRIHitmUgR(void *p) {
      delete [] ((vector<NIGIRIHit*>*)p);
   }
   static void destruct_vectorlENIGIRIHitmUgR(void *p) {
      typedef vector<NIGIRIHit*> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<NIGIRIHit*>

namespace ROOTDict {
   void vectorlEunsignedsPshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEunsignedsPshortgR_Dictionary();
   static void *new_vectorlEunsignedsPshortgR(void *p = 0);
   static void *newArray_vectorlEunsignedsPshortgR(Long_t size, void *p);
   static void delete_vectorlEunsignedsPshortgR(void *p);
   static void deleteArray_vectorlEunsignedsPshortgR(void *p);
   static void destruct_vectorlEunsignedsPshortgR(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<unsigned short>*)
   {
      vector<unsigned short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<unsigned short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<unsigned short>", -2, "vector.dll", 0,
                  typeid(vector<unsigned short>), ::ROOT::DefineBehavior(ptr, ptr),
                  0, &vectorlEunsignedsPshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<unsigned short>) );
      instance.SetNew(&new_vectorlEunsignedsPshortgR);
      instance.SetNewArray(&newArray_vectorlEunsignedsPshortgR);
      instance.SetDelete(&delete_vectorlEunsignedsPshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEunsignedsPshortgR);
      instance.SetDestructor(&destruct_vectorlEunsignedsPshortgR);
      instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<unsigned short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<unsigned short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEunsignedsPshortgR_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const vector<unsigned short>*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_vectorlEunsignedsPshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short> : new vector<unsigned short>;
   }
   static void *newArray_vectorlEunsignedsPshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<unsigned short>[nElements] : new vector<unsigned short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEunsignedsPshortgR(void *p) {
      delete ((vector<unsigned short>*)p);
   }
   static void deleteArray_vectorlEunsignedsPshortgR(void *p) {
      delete [] ((vector<unsigned short>*)p);
   }
   static void destruct_vectorlEunsignedsPshortgR(void *p) {
      typedef vector<unsigned short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class vector<unsigned short>

/********************************************************
* DataStruct_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDataStruct_dict();

extern "C" void G__set_cpp_environmentDataStruct_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("libDataStruct.h");
  G__cpp_reset_tagtableDataStruct_dict();
}
#include <new>
extern "C" int G__cpp_dllrevDataStruct_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TDCHit */
static int G__DataStruct_dict_424_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDCHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDCHit[n];
     } else {
       p = new((void*) gvp) TDCHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDCHit;
     } else {
       p = new((void*) gvp) TDCHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDCHit*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TDCHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDCHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TDCHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TDCHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDCHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDCHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDCHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDCHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_424_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDCHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataStruct_dict_424_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TDCHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TDCHit(*(TDCHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TDCHit G__TTDCHit;
static int G__DataStruct_dict_424_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TDCHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TDCHit*) (soff+(sizeof(TDCHit)*i)))->~G__TTDCHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TDCHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TDCHit*) (soff))->~G__TTDCHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DataStruct_dict_424_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDCHit* dest = (TDCHit*) G__getstructoffset();
   *dest = *(TDCHit*) libp->para[0].ref;
   const TDCHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* NIGIRIHit */
static int G__DataStruct_dict_425_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NIGIRIHit* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NIGIRIHit[n];
     } else {
       p = new((void*) gvp) NIGIRIHit[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NIGIRIHit;
     } else {
       p = new((void*) gvp) NIGIRIHit;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRIHit*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRIHit*) G__getstructoffset())->AddTDCHit((UShort_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRIHit*) G__getstructoffset())->AddQDCHit((UShort_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRIHit*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NIGIRIHit::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRIHit::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NIGIRIHit::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NIGIRIHit::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRIHit*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRIHit::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NIGIRIHit::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRIHit::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_425_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NIGIRIHit::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataStruct_dict_425_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NIGIRIHit* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NIGIRIHit(*(NIGIRIHit*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NIGIRIHit G__TNIGIRIHit;
static int G__DataStruct_dict_425_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NIGIRIHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NIGIRIHit*) (soff+(sizeof(NIGIRIHit)*i)))->~G__TNIGIRIHit();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NIGIRIHit*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NIGIRIHit*) (soff))->~G__TNIGIRIHit();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DataStruct_dict_425_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NIGIRIHit* dest = (NIGIRIHit*) G__getstructoffset();
   *dest = *(NIGIRIHit*) libp->para[0].ref;
   const NIGIRIHit& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* NIGIRI */
static int G__DataStruct_dict_426_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NIGIRI* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NIGIRI[n];
     } else {
       p = new((void*) gvp) NIGIRI[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new NIGIRI;
     } else {
       p = new((void*) gvp) NIGIRI;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRI*) G__getstructoffset())->Clear();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((NIGIRI*) G__getstructoffset())->GetMult());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((NIGIRI*) G__getstructoffset())->GetHit((unsigned short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRI*) G__getstructoffset())->AddHit((NIGIRIHit*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) NIGIRI::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRI::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) NIGIRI::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      NIGIRI::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((NIGIRI*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRI::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NIGIRI::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) NIGIRI::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__DataStruct_dict_426_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) NIGIRI::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__DataStruct_dict_426_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   NIGIRI* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new NIGIRI(*(NIGIRI*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef NIGIRI G__TNIGIRI;
static int G__DataStruct_dict_426_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (NIGIRI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((NIGIRI*) (soff+(sizeof(NIGIRI)*i)))->~G__TNIGIRI();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (NIGIRI*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((NIGIRI*) (soff))->~G__TNIGIRI();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__DataStruct_dict_426_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   NIGIRI* dest = (NIGIRI*) G__getstructoffset();
   *dest = *(NIGIRI*) libp->para[0].ref;
   const NIGIRI& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TDCHit */

/* NIGIRIHit */

/* NIGIRI */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDataStruct_dict {
 public:
  G__Sizep2memfuncDataStruct_dict(): p(&G__Sizep2memfuncDataStruct_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDataStruct_dict::*p)();
};

size_t G__get_sizep2memfuncDataStruct_dict()
{
  G__Sizep2memfuncDataStruct_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDataStruct_dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit))) {
     TDCHit *G__Lderived;
     G__Lderived=(TDCHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit),G__get_linked_tagnum(&G__DataStruct_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit))) {
     NIGIRIHit *G__Lderived;
     G__Lderived=(NIGIRIHit*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit),G__get_linked_tagnum(&G__DataStruct_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI))) {
     NIGIRI *G__Lderived;
     G__Lderived=(NIGIRI*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI),G__get_linked_tagnum(&G__DataStruct_dictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDataStruct_dict() {

   /* Setting up typedef entry */
   G__search_typename2("UShort_t",114,-1,0,-1);
   G__setnewtype(-1,"Unsigned Short integer 2 bytes (unsigned short)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UShort_t>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<NIGIRIHit*>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TDCHit */
static void G__setup_memvarTDCHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit));
   { TDCHit *p; p=(TDCHit*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->ch)-(long)(p)),114,0,0,-1,G__defined_typename("UShort_t"),-1,1,"ch=",0,"channel number");
   G__memvar_setup((void*)((long)(&p->t)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"t=",0,"baseline");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* NIGIRIHit */
static void G__setup_memvarNIGIRIHit(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit));
   { NIGIRIHit *p; p=(NIGIRIHit*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->evt_type)-(long)(p)),99,0,0,-1,G__defined_typename("Char_t"),-1,1,"evt_type=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->overrange)-(long)(p)),99,0,0,-1,G__defined_typename("Char_t"),-1,1,"overrange=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->losttrigger)-(long)(p)),99,0,0,-1,G__defined_typename("Char_t"),-1,1,"losttrigger=",0,"trigger lost flag (=1: lost)");
   G__memvar_setup((void*)((long)(&p->evt)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"evt=",0,"evt number");
   G__memvar_setup((void*)((long)(&p->b)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"b=",0,"board number");
   G__memvar_setup((void*)((long)(&p->ch)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"ch=",0,"channel number");
   G__memvar_setup((void*)((long)(&p->ts)-(long)(p)),109,0,0,-1,G__defined_typename("ULong64_t"),-1,1,"ts=",0,"timestamp");
   G__memvar_setup((void*)((long)(&p->finets)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"finets=",0,"finets");
   G__memvar_setup((void*)((long)(&p->cshort)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"cshort=",0,"charge short");
   G__memvar_setup((void*)((long)(&p->clong)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"clong=",0,"charge long");
   G__memvar_setup((void*)((long)(&p->baseline)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"baseline=",0,"baseline");
   G__memvar_setup((void*)((long)(&p->nsample)-(long)(p)),115,0,0,-1,G__defined_typename("Short_t"),-1,1,"nsample=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->pulse)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"pulse=",0,"pulse");
   G__memvar_setup((void*)((long)(&p->tdcmult)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"tdcmult=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tdc_ch)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"tdc_ch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tdc_t)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"tdc_t=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->qdcmult)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"qdcmult=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->qdc_ch)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"qdc_ch=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->qdc_h)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR),G__defined_typename("vector<UShort_t>"),-1,1,"qdc_h=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* NIGIRI */
static void G__setup_memvarNIGIRI(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI));
   { NIGIRI *p; p=(NIGIRI*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fmult)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fmult=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fhits)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR),G__defined_typename("vector<NIGIRIHit*>"),-1,1,"fhits=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__DataStruct_dictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDataStruct_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTDCHit(void) {
   /* TDCHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit));
   G__memfunc_setup("TDCHit",512,G__DataStruct_dict_424_0_1, 105, G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__DataStruct_dict_424_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataStruct_dict_424_0_3, 85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDCHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataStruct_dict_424_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDCHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataStruct_dict_424_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDCHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataStruct_dict_424_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDCHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataStruct_dict_424_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataStruct_dict_424_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDCHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataStruct_dict_424_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDCHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataStruct_dict_424_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDCHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataStruct_dict_424_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDCHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TDCHit", 512, G__DataStruct_dict_424_0_15, (int) ('i'), G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit), -1, 0, 1, 1, 1, 0, "u 'TDCHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TDCHit", 638, G__DataStruct_dict_424_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DataStruct_dict_424_0_17, (int) ('u'), G__get_linked_tagnum(&G__DataStruct_dictLN_TDCHit), -1, 1, 1, 1, 1, 0, "u 'TDCHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncNIGIRIHit(void) {
   /* NIGIRIHit */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit));
   G__memfunc_setup("NIGIRIHit",743,G__DataStruct_dict_425_0_1, 105, G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__DataStruct_dict_425_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddTDCHit",777,G__DataStruct_dict_425_0_3, 121, -1, -1, 0, 2, 1, 1, 0, 
"r - 'UShort_t' 0 - ch i - 'Int_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddQDCHit",774,G__DataStruct_dict_425_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"r - 'UShort_t' 0 - ch i - 'Int_t' 0 - t", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__DataStruct_dict_425_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataStruct_dict_425_0_6, 85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NIGIRIHit::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataStruct_dict_425_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRIHit::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataStruct_dict_425_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NIGIRIHit::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataStruct_dict_425_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NIGIRIHit::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataStruct_dict_425_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataStruct_dict_425_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRIHit::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataStruct_dict_425_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NIGIRIHit::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataStruct_dict_425_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRIHit::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataStruct_dict_425_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NIGIRIHit::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NIGIRIHit", 743, G__DataStruct_dict_425_0_18, (int) ('i'), G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit), -1, 0, 1, 1, 1, 0, "u 'NIGIRIHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NIGIRIHit", 869, G__DataStruct_dict_425_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DataStruct_dict_425_0_20, (int) ('u'), G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit), -1, 1, 1, 1, 1, 0, "u 'NIGIRIHit' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncNIGIRI(void) {
   /* NIGIRI */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI));
   G__memfunc_setup("NIGIRI",450,G__DataStruct_dict_426_0_1, 105, G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Clear",487,G__DataStruct_dict_426_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetMult",706,G__DataStruct_dict_426_0_3, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHit",581,G__DataStruct_dict_426_0_4, 85, G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRIHit), -1, 0, 1, 1, 1, 0, "r - - 0 - n", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AddHit",558,G__DataStruct_dict_426_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "U 'NIGIRIHit' - 0 - hit", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__DataStruct_dict_426_0_6, 85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&NIGIRI::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__DataStruct_dict_426_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRI::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__DataStruct_dict_426_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&NIGIRI::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__DataStruct_dict_426_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&NIGIRI::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__DataStruct_dictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__DataStruct_dict_426_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__DataStruct_dict_426_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRI::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__DataStruct_dict_426_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NIGIRI::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__DataStruct_dict_426_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&NIGIRI::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__DataStruct_dict_426_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&NIGIRI::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("NIGIRI", 450, G__DataStruct_dict_426_0_18, (int) ('i'), G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI), -1, 0, 1, 1, 1, 0, "u 'NIGIRI' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~NIGIRI", 576, G__DataStruct_dict_426_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__DataStruct_dict_426_0_20, (int) ('u'), G__get_linked_tagnum(&G__DataStruct_dictLN_NIGIRI), -1, 1, 1, 1, 1, 0, "u 'NIGIRI' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDataStruct_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDataStruct_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDataStruct_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__DataStruct_dictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR = { "vector<unsigned short,allocator<unsigned short> >" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__DataStruct_dictLN_TDCHit = { "TDCHit" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_NIGIRIHit = { "NIGIRIHit" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_NIGIRI = { "NIGIRI" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR = { "vector<NIGIRIHit*,allocator<NIGIRIHit*> >" , 99 , -1 };
G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<NIGIRIHit*,allocator<NIGIRIHit*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDataStruct_dict() {
  G__DataStruct_dictLN_TClass.tagnum = -1 ;
  G__DataStruct_dictLN_TBuffer.tagnum = -1 ;
  G__DataStruct_dictLN_TMemberInspector.tagnum = -1 ;
  G__DataStruct_dictLN_TObject.tagnum = -1 ;
  G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR.tagnum = -1 ;
  G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__DataStruct_dictLN_TDCHit.tagnum = -1 ;
  G__DataStruct_dictLN_NIGIRIHit.tagnum = -1 ;
  G__DataStruct_dictLN_NIGIRI.tagnum = -1 ;
  G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR.tagnum = -1 ;
  G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDataStruct_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_TClass);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_TObject);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_TDCHit),sizeof(TDCHit),-1,292096,(char*)NULL,G__setup_memvarTDCHit,G__setup_memfuncTDCHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_NIGIRIHit),sizeof(NIGIRIHit),-1,292096,(char*)NULL,G__setup_memvarNIGIRIHit,G__setup_memfuncNIGIRIHit);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_NIGIRI),sizeof(NIGIRI),-1,292096,(char*)NULL,G__setup_memvarNIGIRI,G__setup_memfuncNIGIRI);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupDataStruct_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupDataStruct_dict()");
  G__set_cpp_environmentDataStruct_dict();
  G__cpp_setup_tagtableDataStruct_dict();

  G__cpp_setup_inheritanceDataStruct_dict();

  G__cpp_setup_typetableDataStruct_dict();

  G__cpp_setup_memvarDataStruct_dict();

  G__cpp_setup_memfuncDataStruct_dict();
  G__cpp_setup_globalDataStruct_dict();
  G__cpp_setup_funcDataStruct_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDataStruct_dict();
  return;
}
class G__cpp_setup_initDataStruct_dict {
  public:
    G__cpp_setup_initDataStruct_dict() { G__add_setup_func("DataStruct_dict",(G__incsetup)(&G__cpp_setupDataStruct_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDataStruct_dict() { G__remove_setup_func("DataStruct_dict"); }
};
G__cpp_setup_initDataStruct_dict G__cpp_setup_initializerDataStruct_dict;

