/********************************************************************
* DataStruct_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DataStruct_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDataStruct_dict();
extern void G__cpp_setup_inheritanceDataStruct_dict();
extern void G__cpp_setup_typetableDataStruct_dict();
extern void G__cpp_setup_memvarDataStruct_dict();
extern void G__cpp_setup_globalDataStruct_dict();
extern void G__cpp_setup_memfuncDataStruct_dict();
extern void G__cpp_setup_funcDataStruct_dict();
extern void G__set_cpp_environmentDataStruct_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "libDataStruct.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DataStruct_dictLN_TClass;
extern G__linked_taginfo G__DataStruct_dictLN_TBuffer;
extern G__linked_taginfo G__DataStruct_dictLN_TMemberInspector;
extern G__linked_taginfo G__DataStruct_dictLN_TObject;
extern G__linked_taginfo G__DataStruct_dictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__DataStruct_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataStruct_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DataStruct_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DataStruct_dictLN_TDCHit;
extern G__linked_taginfo G__DataStruct_dictLN_NIGIRIHit;
extern G__linked_taginfo G__DataStruct_dictLN_NIGIRI;
extern G__linked_taginfo G__DataStruct_dictLN_vectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgR;
extern G__linked_taginfo G__DataStruct_dictLN_reverse_iteratorlEvectorlENIGIRIHitmUcOallocatorlENIGIRIHitmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
