/********************************************************************
* pdecoder_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error pdecoder_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablepdecoder_dict();
extern void G__cpp_setup_inheritancepdecoder_dict();
extern void G__cpp_setup_typetablepdecoder_dict();
extern void G__cpp_setup_memvarpdecoder_dict();
extern void G__cpp_setup_globalpdecoder_dict();
extern void G__cpp_setup_memfuncpdecoder_dict();
extern void G__cpp_setup_funcpdecoder_dict();
extern void G__set_cpp_environmentpdecoder_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "pdecoder.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__pdecoder_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__pdecoder_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pdecoder_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__pdecoder_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__pdecoder_dictLN_Event;

/* STUB derived class for protected member access */
