//
// File generated by rootcint at Thu Jul 11 21:55:11 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME Xfer_dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Xfer_dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::block_header block_header;
      #else
      class block_header  {
         public:
         //friend XX;
         unsigned short hdr_flags; //see below */
         unsigned short hdr_stream; //=0 for forced ack request or 1=>MAX_STREAM  */
         unsigned short hdr_endian; //data byte order */
         unsigned short hdr_ID; //
         unsigned int hdr_sequence; //for this stream */
         unsigned int hdr_blocklength; //total length of this block including the header */
         unsigned int hdr_datalength; //length of user data in the block  */
         unsigned int hdr_offset; //very large blocks may be fragmented  */
         unsigned int hdr_id1; //for spy to locate header  =0x19062002 */
         unsigned int hdr_id2; //for spy to locate header  =0x09592400 */
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::mbs_block_header mbs_block_header;
      #else
      class mbs_block_header  {
         public:
         //friend XX;
         unsigned int mbs_endian; //
         unsigned int mbs_blocksize; //
      };
      #endif

      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::ack ack;
      #else
      class ack  {
         public:
         //friend XX;
         unsigned short acq_flags; //bit 0 = 1 for ack  */
         unsigned short acq_code; //=0 for good ack otherwise error reason */
         unsigned short acq_ts_state; //tape server state - see below */
         unsigned short acq_stream; //=0 for forced ack ack or 1=>MAX_STREAM  */
         unsigned short acq_endian; //=1 transmitted in host byte order */
         unsigned short acq_ID; //value of ID variable  0 => */
         unsigned int acq_sequence; //for stream != 0 is sequence being acked */
         unsigned short acq_stream_state1; //see below  */
         unsigned short acq_stream_state2; //*/
         unsigned short acq_stream_state3; //*/
         unsigned short acq_stream_state4; //*/
         unsigned short acq_stream_window1; //*/
         unsigned short acq_stream_window2; //*/
         unsigned short acq_stream_window3; //*/
         unsigned short acq_stream_window4; //*/
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void block_header_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void block_header_Dictionary();
   static void *new_block_header(void *p = 0);
   static void *newArray_block_header(Long_t size, void *p);
   static void delete_block_header(void *p);
   static void deleteArray_block_header(void *p);
   static void destruct_block_header(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::block_header*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::block_header) == sizeof( ::ROOTShadow::Shadow::block_header));
      ::block_header *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::block_header),0);
      static ::ROOT::TGenericClassInfo 
         instance("block_header", "./transfer.h", 19,
                  typeid(::block_header), ::ROOT::DefineBehavior(ptr, ptr),
                  &block_header_ShowMembers, &block_header_Dictionary, isa_proxy, 4,
                  sizeof(::block_header) );
      instance.SetNew(&new_block_header);
      instance.SetNewArray(&newArray_block_header);
      instance.SetDelete(&delete_block_header);
      instance.SetDeleteArray(&deleteArray_block_header);
      instance.SetDestructor(&destruct_block_header);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::block_header*)
   {
      return GenerateInitInstanceLocal((::block_header*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::block_header*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void block_header_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::block_header*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void mbs_block_header_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void mbs_block_header_Dictionary();
   static void *new_mbs_block_header(void *p = 0);
   static void *newArray_mbs_block_header(Long_t size, void *p);
   static void delete_mbs_block_header(void *p);
   static void deleteArray_mbs_block_header(void *p);
   static void destruct_mbs_block_header(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::mbs_block_header*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::mbs_block_header) == sizeof( ::ROOTShadow::Shadow::mbs_block_header));
      ::mbs_block_header *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::mbs_block_header),0);
      static ::ROOT::TGenericClassInfo 
         instance("mbs_block_header", "./transfer.h", 27,
                  typeid(::mbs_block_header), ::ROOT::DefineBehavior(ptr, ptr),
                  &mbs_block_header_ShowMembers, &mbs_block_header_Dictionary, isa_proxy, 4,
                  sizeof(::mbs_block_header) );
      instance.SetNew(&new_mbs_block_header);
      instance.SetNewArray(&newArray_mbs_block_header);
      instance.SetDelete(&delete_mbs_block_header);
      instance.SetDeleteArray(&deleteArray_mbs_block_header);
      instance.SetDestructor(&destruct_mbs_block_header);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::mbs_block_header*)
   {
      return GenerateInitInstanceLocal((::mbs_block_header*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::mbs_block_header*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void mbs_block_header_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::mbs_block_header*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

namespace ROOTDict {
   void ack_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void ack_Dictionary();
   static void *new_ack(void *p = 0);
   static void *newArray_ack(Long_t size, void *p);
   static void delete_ack(void *p);
   static void deleteArray_ack(void *p);
   static void destruct_ack(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::ack*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::ack) == sizeof( ::ROOTShadow::Shadow::ack));
      ::ack *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::ack),0);
      static ::ROOT::TGenericClassInfo 
         instance("ack", "./transfer.h", 46,
                  typeid(::ack), ::ROOT::DefineBehavior(ptr, ptr),
                  &ack_ShowMembers, &ack_Dictionary, isa_proxy, 4,
                  sizeof(::ack) );
      instance.SetNew(&new_ack);
      instance.SetNewArray(&newArray_ack);
      instance.SetDelete(&delete_ack);
      instance.SetDeleteArray(&deleteArray_ack);
      instance.SetDestructor(&destruct_ack);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::ack*)
   {
      return GenerateInitInstanceLocal((::ack*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ack*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void ack_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::ack*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
namespace ROOTDict {
   void block_header_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class block_header.
      typedef ::ROOTShadow::Shadow::block_header ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::block_header*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_flags", &sobj->hdr_flags);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_stream", &sobj->hdr_stream);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_endian", &sobj->hdr_endian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_ID", &sobj->hdr_ID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_sequence", &sobj->hdr_sequence);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_blocklength", &sobj->hdr_blocklength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_datalength", &sobj->hdr_datalength);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_offset", &sobj->hdr_offset);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_id1", &sobj->hdr_id1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hdr_id2", &sobj->hdr_id2);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_block_header(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::block_header : new ::block_header;
   }
   static void *newArray_block_header(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::block_header[nElements] : new ::block_header[nElements];
   }
   // Wrapper around operator delete
   static void delete_block_header(void *p) {
      delete ((::block_header*)p);
   }
   static void deleteArray_block_header(void *p) {
      delete [] ((::block_header*)p);
   }
   static void destruct_block_header(void *p) {
      typedef ::block_header current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::block_header

//______________________________________________________________________________
namespace ROOTDict {
   void mbs_block_header_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class mbs_block_header.
      typedef ::ROOTShadow::Shadow::mbs_block_header ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::mbs_block_header*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mbs_endian", &sobj->mbs_endian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "mbs_blocksize", &sobj->mbs_blocksize);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_mbs_block_header(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mbs_block_header : new ::mbs_block_header;
   }
   static void *newArray_mbs_block_header(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::mbs_block_header[nElements] : new ::mbs_block_header[nElements];
   }
   // Wrapper around operator delete
   static void delete_mbs_block_header(void *p) {
      delete ((::mbs_block_header*)p);
   }
   static void deleteArray_mbs_block_header(void *p) {
      delete [] ((::mbs_block_header*)p);
   }
   static void destruct_mbs_block_header(void *p) {
      typedef ::mbs_block_header current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::mbs_block_header

//______________________________________________________________________________
namespace ROOTDict {
   void ack_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class ack.
      typedef ::ROOTShadow::Shadow::ack ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::ack*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_flags", &sobj->acq_flags);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_code", &sobj->acq_code);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_ts_state", &sobj->acq_ts_state);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream", &sobj->acq_stream);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_endian", &sobj->acq_endian);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_ID", &sobj->acq_ID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_sequence", &sobj->acq_sequence);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_state1", &sobj->acq_stream_state1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_state2", &sobj->acq_stream_state2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_state3", &sobj->acq_stream_state3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_state4", &sobj->acq_stream_state4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_window1", &sobj->acq_stream_window1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_window2", &sobj->acq_stream_window2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_window3", &sobj->acq_stream_window3);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "acq_stream_window4", &sobj->acq_stream_window4);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_ack(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ack : new ::ack;
   }
   static void *newArray_ack(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::ack[nElements] : new ::ack[nElements];
   }
   // Wrapper around operator delete
   static void delete_ack(void *p) {
      delete ((::ack*)p);
   }
   static void deleteArray_ack(void *p) {
      delete [] ((::ack*)p);
   }
   static void destruct_ack(void *p) {
      typedef ::ack current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::ack

/********************************************************
* Xfer_dict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableXfer_dict();

extern "C" void G__set_cpp_environmentXfer_dict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("transfer.h");
  G__cpp_reset_tagtableXfer_dict();
}
#include <new>
extern "C" int G__cpp_dllrevXfer_dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* block_header */
// automatic default constructor
static int G__Xfer_dict_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   block_header *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new block_header[n];
     } else {
       p = new((void*) gvp) block_header[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new block_header;
     } else {
       p = new((void*) gvp) block_header;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_block_header));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Xfer_dict_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   block_header* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new block_header(*(block_header*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_block_header));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef block_header G__Tblock_header;
static int G__Xfer_dict_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (block_header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((block_header*) (soff+(sizeof(block_header)*i)))->~G__Tblock_header();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (block_header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((block_header*) (soff))->~G__Tblock_header();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Xfer_dict_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   block_header* dest = (block_header*) G__getstructoffset();
   *dest = *(block_header*) libp->para[0].ref;
   const block_header& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* mbs_block_header */
// automatic default constructor
static int G__Xfer_dict_169_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mbs_block_header *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mbs_block_header[n];
     } else {
       p = new((void*) gvp) mbs_block_header[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new mbs_block_header;
     } else {
       p = new((void*) gvp) mbs_block_header;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Xfer_dict_169_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   mbs_block_header* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new mbs_block_header(*(mbs_block_header*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef mbs_block_header G__Tmbs_block_header;
static int G__Xfer_dict_169_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (mbs_block_header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((mbs_block_header*) (soff+(sizeof(mbs_block_header)*i)))->~G__Tmbs_block_header();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (mbs_block_header*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((mbs_block_header*) (soff))->~G__Tmbs_block_header();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Xfer_dict_169_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   mbs_block_header* dest = (mbs_block_header*) G__getstructoffset();
   *dest = *(mbs_block_header*) libp->para[0].ref;
   const mbs_block_header& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* ack */
// automatic default constructor
static int G__Xfer_dict_170_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ack *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ack[n];
     } else {
       p = new((void*) gvp) ack[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ack;
     } else {
       p = new((void*) gvp) ack;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_ack));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Xfer_dict_170_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ack* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ack(*(ack*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Xfer_dictLN_ack));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ack G__Tack;
static int G__Xfer_dict_170_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ack*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ack*) (soff+(sizeof(ack)*i)))->~G__Tack();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ack*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ack*) (soff))->~G__Tack();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Xfer_dict_170_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ack* dest = (ack*) G__getstructoffset();
   *dest = *(ack*) libp->para[0].ref;
   const ack& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__Xfer_dict__0_2180(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferTxData((char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2181(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferTxRestart());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2182(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferBlockSize((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2183(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMode((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2184(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferBlockMode((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2185(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferEndian((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2186(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferPort((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2187(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferInit((char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2188(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      transferClose();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2189(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferStatus());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2190(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferSetVerbose((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2191(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferSetUser((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2192(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferNice((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2193(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferUseOverlap((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2194(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferTxWait());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2195(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferState());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2196(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferSndBufSize((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2197(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferRcvBufSize((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2198(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiTxData((int) G__int(libp->para[0]), (char*) G__int(libp->para[1])
, (int) G__int(libp->para[2]), (int) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2199(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiTxRestart((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2200(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiBlockSize((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2201(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiMode((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2202(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiBlockMode((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2203(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiEndian((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2204(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiPort((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2205(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiInit((int) G__int(libp->para[0]), (char*) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2206(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      transferMultiClose((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2207(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiStatus((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2208(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiNice((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2209(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiUseOverlap((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2210(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiTxWait((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2211(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiState((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2212(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiSndBufSize((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Xfer_dict__0_2213(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) transferMultiRcvBufSize((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* block_header */

/* mbs_block_header */

/* ack */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncXfer_dict {
 public:
  G__Sizep2memfuncXfer_dict(): p(&G__Sizep2memfuncXfer_dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncXfer_dict::*p)();
};

size_t G__get_sizep2memfuncXfer_dict()
{
  G__Sizep2memfuncXfer_dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceXfer_dict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableXfer_dict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("HEADER",117,G__get_linked_tagnum(&G__Xfer_dictLN_block_header),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("MBS_BLKHEADER",117,G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("ACK",117,G__get_linked_tagnum(&G__Xfer_dictLN_ack),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* block_header */
static void G__setup_memvarblock_header(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Xfer_dictLN_block_header));
   { block_header *p; p=(block_header*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->hdr_flags)-(long)(p)),114,0,0,-1,-1,-1,1,"hdr_flags=",0,"see below */");
   G__memvar_setup((void*)((long)(&p->hdr_stream)-(long)(p)),114,0,0,-1,-1,-1,1,"hdr_stream=",0,"=0 for forced ack request or 1=>MAX_STREAM  */");
   G__memvar_setup((void*)((long)(&p->hdr_endian)-(long)(p)),114,0,0,-1,-1,-1,1,"hdr_endian=",0,"data byte order */");
   G__memvar_setup((void*)((long)(&p->hdr_ID)-(long)(p)),114,0,0,-1,-1,-1,1,"hdr_ID=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->hdr_sequence)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_sequence=",0,"for this stream */");
   G__memvar_setup((void*)((long)(&p->hdr_blocklength)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_blocklength=",0,"total length of this block including the header */");
   G__memvar_setup((void*)((long)(&p->hdr_datalength)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_datalength=",0,"length of user data in the block  */");
   G__memvar_setup((void*)((long)(&p->hdr_offset)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_offset=",0,"very large blocks may be fragmented  */");
   G__memvar_setup((void*)((long)(&p->hdr_id1)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_id1=",0,"for spy to locate header  =0x19062002 */");
   G__memvar_setup((void*)((long)(&p->hdr_id2)-(long)(p)),104,0,0,-1,-1,-1,1,"hdr_id2=",0,"for spy to locate header  =0x09592400 */");
   }
   G__tag_memvar_reset();
}


   /* mbs_block_header */
static void G__setup_memvarmbs_block_header(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header));
   { mbs_block_header *p; p=(mbs_block_header*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->mbs_endian)-(long)(p)),104,0,0,-1,-1,-1,1,"mbs_endian=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->mbs_blocksize)-(long)(p)),104,0,0,-1,-1,-1,1,"mbs_blocksize=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* ack */
static void G__setup_memvarack(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Xfer_dictLN_ack));
   { ack *p; p=(ack*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->acq_flags)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_flags=",0,"bit 0 = 1 for ack  */");
   G__memvar_setup((void*)((long)(&p->acq_code)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_code=",0,"=0 for good ack otherwise error reason */");
   G__memvar_setup((void*)((long)(&p->acq_ts_state)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_ts_state=",0,"tape server state - see below */");
   G__memvar_setup((void*)((long)(&p->acq_stream)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream=",0,"=0 for forced ack ack or 1=>MAX_STREAM  */");
   G__memvar_setup((void*)((long)(&p->acq_endian)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_endian=",0,"=1 transmitted in host byte order */");
   G__memvar_setup((void*)((long)(&p->acq_ID)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_ID=",0,"value of ID variable  0 => */");
   G__memvar_setup((void*)((long)(&p->acq_sequence)-(long)(p)),104,0,0,-1,-1,-1,1,"acq_sequence=",0,"for stream != 0 is sequence being acked */");
   G__memvar_setup((void*)((long)(&p->acq_stream_state1)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_state1=",0,"see below  */");
   G__memvar_setup((void*)((long)(&p->acq_stream_state2)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_state2=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_state3)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_state3=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_state4)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_state4=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_window1)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_window1=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_window2)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_window2=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_window3)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_window3=",0,"*/");
   G__memvar_setup((void*)((long)(&p->acq_stream_window4)-(long)(p)),114,0,0,-1,-1,-1,1,"acq_stream_window4=",0,"*/");
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarXfer_dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncblock_header(void) {
   /* block_header */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Xfer_dictLN_block_header));
   // automatic default constructor
   G__memfunc_setup("block_header", 1235, G__Xfer_dict_168_0_1, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_block_header), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("block_header", 1235, G__Xfer_dict_168_0_2, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_block_header), -1, 0, 1, 1, 1, 0, "u 'block_header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~block_header", 1361, G__Xfer_dict_168_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Xfer_dict_168_0_4, (int) ('u'), G__get_linked_tagnum(&G__Xfer_dictLN_block_header), -1, 1, 1, 1, 1, 0, "u 'block_header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncmbs_block_header(void) {
   /* mbs_block_header */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header));
   // automatic default constructor
   G__memfunc_setup("mbs_block_header", 1652, G__Xfer_dict_169_0_1, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("mbs_block_header", 1652, G__Xfer_dict_169_0_2, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header), -1, 0, 1, 1, 1, 0, "u 'mbs_block_header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~mbs_block_header", 1778, G__Xfer_dict_169_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Xfer_dict_169_0_4, (int) ('u'), G__get_linked_tagnum(&G__Xfer_dictLN_mbs_block_header), -1, 1, 1, 1, 1, 0, "u 'mbs_block_header' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncack(void) {
   /* ack */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Xfer_dictLN_ack));
   // automatic default constructor
   G__memfunc_setup("ack", 303, G__Xfer_dict_170_0_1, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_ack), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("ack", 303, G__Xfer_dict_170_0_2, (int) ('i'), G__get_linked_tagnum(&G__Xfer_dictLN_ack), -1, 0, 1, 1, 1, 0, "u 'ack' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ack", 429, G__Xfer_dict_170_0_3, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Xfer_dict_170_0_4, (int) ('u'), G__get_linked_tagnum(&G__Xfer_dictLN_ack), -1, 1, 1, 1, 1, 0, "u 'ack' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncXfer_dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"INCtransferh=0",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"MAX_STREAM=4",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"MAXPORTS=8",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"HDR_ID1=419831810",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"HDR_ID2=156836864",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"OK=0",1,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,112,0,0,-1,-1,-1,1,"ERROR=-1",1,(char*)NULL);

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalXfer_dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
   G__memfunc_setup("transferTxData", 1451, G__Xfer_dict__0_2180, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 0 - - i - - 0 - - "
"i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferTxRestart", 1814, G__Xfer_dict__0_2181, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferBlockSize", 1771, G__Xfer_dict__0_2182, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMode", 1258, G__Xfer_dict__0_2183, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferBlockMode", 1749, G__Xfer_dict__0_2184, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferEndian", 1460, G__Xfer_dict__0_2185, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferPort", 1290, G__Xfer_dict__0_2186, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferInit", 1273, G__Xfer_dict__0_2187, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferClose", 1371, G__Xfer_dict__0_2188, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferStatus", 1513, G__Xfer_dict__0_2189, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferSetVerbose", 1895, G__Xfer_dict__0_2190, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferSetUser", 1584, G__Xfer_dict__0_2191, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferNice", 1252, G__Xfer_dict__0_2192, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferUseOverlap", 1899, G__Xfer_dict__0_2193, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferTxWait", 1478, G__Xfer_dict__0_2194, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferState", 1382, G__Xfer_dict__0_2195, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferSndBufSize", 1858, G__Xfer_dict__0_2196, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferRcvBufSize", 1864, G__Xfer_dict__0_2197, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiTxData", 1974, G__Xfer_dict__0_2198, 105, -1, -1, 0, 4, 1, 1, 0, 
"i - - 0 - - C - - 0 - - "
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiTxRestart", 2337, G__Xfer_dict__0_2199, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiBlockSize", 2294, G__Xfer_dict__0_2200, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiMode", 1781, G__Xfer_dict__0_2201, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiBlockMode", 2272, G__Xfer_dict__0_2202, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiEndian", 1983, G__Xfer_dict__0_2203, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiPort", 1813, G__Xfer_dict__0_2204, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiInit", 1796, G__Xfer_dict__0_2205, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - C - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiClose", 1894, G__Xfer_dict__0_2206, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiStatus", 2036, G__Xfer_dict__0_2207, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiNice", 1775, G__Xfer_dict__0_2208, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiUseOverlap", 2422, G__Xfer_dict__0_2209, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiTxWait", 2001, G__Xfer_dict__0_2210, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiState", 1905, G__Xfer_dict__0_2211, 105, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiSndBufSize", 2381, G__Xfer_dict__0_2212, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("transferMultiRcvBufSize", 2387, G__Xfer_dict__0_2213, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - - i - - 0 - -", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcXfer_dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Xfer_dictLN_block_header = { "block_header" , 115 , -1 };
G__linked_taginfo G__Xfer_dictLN_mbs_block_header = { "mbs_block_header" , 115 , -1 };
G__linked_taginfo G__Xfer_dictLN_ack = { "ack" , 115 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableXfer_dict() {
  G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Xfer_dictLN_block_header.tagnum = -1 ;
  G__Xfer_dictLN_mbs_block_header.tagnum = -1 ;
  G__Xfer_dictLN_ack.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableXfer_dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Xfer_dictLN_block_header),sizeof(block_header),-1,262144,(char*)NULL,G__setup_memvarblock_header,G__setup_memfuncblock_header);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Xfer_dictLN_mbs_block_header),sizeof(mbs_block_header),-1,262144,(char*)NULL,G__setup_memvarmbs_block_header,G__setup_memfuncmbs_block_header);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Xfer_dictLN_ack),sizeof(ack),-1,262144,(char*)NULL,G__setup_memvarack,G__setup_memfuncack);
}
extern "C" void G__cpp_setupXfer_dict(void) {
  G__check_setup_version(30051515,"G__cpp_setupXfer_dict()");
  G__set_cpp_environmentXfer_dict();
  G__cpp_setup_tagtableXfer_dict();

  G__cpp_setup_inheritanceXfer_dict();

  G__cpp_setup_typetableXfer_dict();

  G__cpp_setup_memvarXfer_dict();

  G__cpp_setup_memfuncXfer_dict();
  G__cpp_setup_globalXfer_dict();
  G__cpp_setup_funcXfer_dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncXfer_dict();
  return;
}
class G__cpp_setup_initXfer_dict {
  public:
    G__cpp_setup_initXfer_dict() { G__add_setup_func("Xfer_dict",(G__incsetup)(&G__cpp_setupXfer_dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initXfer_dict() { G__remove_setup_func("Xfer_dict"); }
};
G__cpp_setup_initXfer_dict G__cpp_setup_initializerXfer_dict;

