/********************************************************************
* Xfer_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error Xfer_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableXfer_dict();
extern void G__cpp_setup_inheritanceXfer_dict();
extern void G__cpp_setup_typetableXfer_dict();
extern void G__cpp_setup_memvarXfer_dict();
extern void G__cpp_setup_globalXfer_dict();
extern void G__cpp_setup_memfuncXfer_dict();
extern void G__cpp_setup_funcXfer_dict();
extern void G__set_cpp_environmentXfer_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "transfer.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__Xfer_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__Xfer_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Xfer_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__Xfer_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__Xfer_dictLN_block_header;
extern G__linked_taginfo G__Xfer_dictLN_mbs_block_header;
extern G__linked_taginfo G__Xfer_dictLN_ack;

/* STUB derived class for protected member access */
